import type { Track, TrackChannel, Keyframe, PropertyKeyframe } from '../types/animator';
import { TRACK_CHANNELS } from '../types/animator';
import { generateId } from './idGenerator';
export interface KeyframeCopyPayload { channels: Partial<Record<TrackChannel, Array<Omit<PropertyKeyframe, 'id'>>>>; maskChannels?: Record<string, Array<Omit<PropertyKeyframe, 'id'>>>; maskPathChannels?: Record<string, Array<Omit<PropertyKeyframe, 'id'>>>; legacy: Array<Omit<Keyframe, 'id'>>; }
export interface PasteKeyframeResult { track: Track; pasted: boolean; }
function cloneKeyframe<T extends { bezierControlPoints?: [number, number, number, number]; value?: unknown }>(keyframe: T): T { return { ...keyframe, ...(keyframe.bezierControlPoints ? { bezierControlPoints: [...keyframe.bezierControlPoints] as [number, number, number, number] } : {}), ...(keyframe.value && typeof keyframe.value === 'object' ? { value: JSON.parse(JSON.stringify(keyframe.value)) } : {}) }; }
function copyMap(map: Record<string, Array<any>> | undefined, frame: number) { return Object.fromEntries(Object.entries(map ?? {}).flatMap(([channel, keyframes]) => { const values = keyframes.filter((keyframe) => keyframe.frame === frame); return values.length ? [[channel, values.map(({ id: _id, ...keyframe }) => cloneKeyframe(keyframe))]] : []; })); }
export function copyKeyframeGroupData(track: Track, frame: number): KeyframeCopyPayload { const channels: KeyframeCopyPayload['channels'] = {}; for (const channel of TRACK_CHANNELS) { const values = (track.channels?.[channel] ?? []).filter((keyframe) => keyframe.frame === frame); if (values.length) channels[channel] = values.map(({ id: _id, ...keyframe }) => cloneKeyframe(keyframe)); } const legacy = (track.keyframes ?? []).filter((keyframe) => keyframe.frame === frame).map(({ id: _id, ...keyframe }) => ({ ...cloneKeyframe(keyframe), transform: { ...keyframe.transform } })); return { channels, maskChannels: copyMap(track.maskChannels, frame), maskPathChannels: copyMap(track.maskPathChannels, frame), legacy }; }
export function pasteKeyframeGroupData(track: Track, targetFrame: number, payload: KeyframeCopyPayload, totalFrames?: number): PasteKeyframeResult { if (!Number.isFinite(targetFrame) || targetFrame < 0 || (totalFrames !== undefined && targetFrame > totalFrames)) return { track, pasted: false }; const channelKeys = TRACK_CHANNELS.filter((channel) => (payload.channels[channel] ?? []).length); const maskKeys = Object.keys(payload.maskChannels ?? {}); const pathKeys = Object.keys(payload.maskPathChannels ?? {}); if (!channelKeys.length && !maskKeys.length && !pathKeys.length && !payload.legacy.length) return { track, pasted: false }; const occupied = (map: Record<string, Array<{ frame: number }>> | undefined) => Object.values(map ?? {}).some((values) => values.some((keyframe) => keyframe.frame === targetFrame)); if (TRACK_CHANNELS.some((channel) => (track.channels?.[channel] ?? []).some((keyframe) => keyframe.frame === targetFrame)) || occupied(track.maskChannels) || occupied(track.maskPathChannels) || (track.keyframes ?? []).some((keyframe) => keyframe.frame === targetFrame)) return { track, pasted: false }; const channels = { ...(track.channels ?? {}) }; for (const channel of channelKeys) channels[channel] = [...(channels[channel] ?? []), ...(payload.channels[channel] ?? []).map((keyframe) => ({ ...cloneKeyframe(keyframe), id: generateId(`pkf_${channel}`), frame: targetFrame }))]; const pasteMap = (source: Record<string, Array<any>>, existing: Record<string, Array<any>> | undefined, prefix: string) => Object.fromEntries([...Object.entries(existing ?? {}), ...Object.entries(source)].map(([channel]) => [channel, [...(existing?.[channel] ?? []), ...(source[channel] ?? []).map((keyframe) => ({ ...cloneKeyframe(keyframe), id: generateId(prefix), frame: targetFrame }))]])); const maskChannels = pasteMap(payload.maskChannels ?? {}, track.maskChannels, 'pkf_mask'); const maskPathChannels = pasteMap(payload.maskPathChannels ?? {}, track.maskPathChannels, 'pkf_mask_path'); const legacy = [...(track.keyframes ?? []), ...payload.legacy.map((keyframe) => ({ ...keyframe, id: generateId('kf'), frame: targetFrame, transform: { ...keyframe.transform } }))]; return { track: { ...track, channels, maskChannels, maskPathChannels, keyframes: legacy }, pasted: true }; }
